= findlibc
C library for reading OCaml findlib META files


This library reads META files directly; it does not use the `findib` library or the `ocamlfind` program.

It does not have a well-organized public API, since it is (currently)
only intended for use by other OBazl libraries such as https://github.com/obazl/mibl[mibl].  If you would like to use it to build your own tool please file an issue.

=== ocamlfind configuration

This is how `findlib` (i.e. `ocamlfind`) is configured.


=== findlib.conf

Default:  `/usr/local/etc/findlib.conf`.

Fields:
*  `path`: used to look up packages
* `destdir`: used to install new packages
* `metadir`: absolute path of metaregistry (see below)


Sample content:

----
destdir="/usr/local/lib/ocaml"
path="/usr/local/lib/ocaml"
ocamlc="ocamlc.opt"
ocamlopt="ocamlopt.opt"
ocamldep="ocamldep.opt"
ocamldoc="ocamldoc.opt"
----

Env var:  `OCAMLFIND_CONF`

=== site-lib

Determined by vars in `findlib.conf`:


=== META

Default: the META file for each package is in the pkg root directory.
This is the layout used by OPAM.

Alternative layout: all META files in one directory, named
`META.<pkgname>`. See
link:http://projects.camlcity.org/projects/dl/findlib-1.9.6/doc/ref-html/r1061.html[site-lib].
